extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
env:
  node: true
  browser: true
plugins:
  - import
  - '@typescript-eslint'
parser: '@typescript-eslint/parser'
rules:
  import/order:
    - warn
    - groups:
        - - builtin
          - external
        - - parent
          - sibling
          - index
      newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: true

  # types
  '@typescript-eslint/no-explicit-any':
    - off
  '@typescript-eslint/ban-types':
    - error
    - types:
        Function: false
        extend-defaults: true
  no-unused-vars:
    - off
  '@typescript-eslint/no-unused-vars':
    - warn
    - vars: all
      args: after-used
      ignoreRestSiblings: false
      argsIgnorePattern: ^_
