version: "3"

services:
  huisheng:
    build:
      context: ./
    env_file: .env
    container_name: huisheng
    volumes:
      - youtube-dl-cache:/var/lib/huisheng/cache
    profiles:
      - production

  huisheng-debug:
    build:
      context: ./
      dockerfile: Dockerfile.debug
    env_file: .env
    container_name: huisheng-debug
    volumes:
      - ./:/app
      - ./.cache:/var/lib/huisheng/cache
    profiles:
      - debug

volumes:
  youtube-dl-cache:
