---
{{- if .Values.credentials.create -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.credentials.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- range $key, $value := .Values.credentials.values }}
  {{ $key }}: {{ b64enc $value }}
  {{- end }}
{{- end -}}
