---
{{- if .Values.credentials.create -}}
{{ $discordBotToken := required "credentials.discordBotToken is required" .Values.credentials.discordBotToken }}
{{ $discordClientId := required "credentials.discordClientId is required" .Values.credentials.discordClientId }}
{{ $minioAccessKey := required "credentials.minioAccessKey is required" .Values.credentials.minioAccessKey }}
{{ $minioSecretKey := required "credentials.minioSecretKey is required" .Values.credentials.minioSecretKey }}
{{ $newRelicLicenseKey := required "credentials.newRelicLicenseKey is required" .Values.credentials.newRelicLicenseKey }}
{{ $youtubeApiKey := required "credentials.youtubeApiKey is required" .Values.credentials.youtubeApiKey }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.credentials.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DISCORD_BOT_TOKEN: {{ $discordBotToken | b64enc }}
  DISCORD_CLIENT_ID: {{ $discordClientId | b64enc }}
  MINIO_ACCESS_KEY: {{ $minioAccessKey | b64enc }}
  MINIO_SECRET_KEY: {{ $minioSecretKey | b64enc }}
  NEW_RELIC_LICENSE_KEY: {{ $newRelicLicenseKey | b64enc }}
  YOUTUBE_API_KEY: {{ $youtubeApiKey | b64enc }}
{{- end -}}
