---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "huisheng.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "huisheng.labels" . | nindent 4}}
spec:
  selector:
    matchLabels: {{ include "huisheng.selectorLabels" . | nindent 6 }}
  replicas: 1
  strategy: 
    type: Recreate
  template:
    metadata:
      labels: {{ include "huisheng.selectorLabels" . | nindent 8 }}
      annotations:
        credentials/checksum: {{ include (print $.Template.BasePath "/credentials.yaml") . | sha256sum }}
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      containers:
        - name: huisheng
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          envFrom:
            - secretRef:
                name: {{ .Values.credentials.secretName }}
          env:
            - name: CACHE_DIR
              value: /data
            {{- range $name, $value := .Values.env }}
            - name: {{ $name }}
              value: {{ $value | toString | quote }}
            {{- end }}
            {{- if .Values.potProvider.enabled }}
            - name: YTDLP_POT_PROVIDER
              value: http://ytdlp-pot-provider:{{ .Values.potProvider.port }}
            {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 10000
            runAsGroup: 10000
            capabilities:
              drop: [ALL]
              add: [SYS_NICE]
          volumeMounts:
            - name: data
              mountPath: /data
        {{- if .Values.potProvider.enabled }}
        - name: ytdlp-pot-provider
          image: {{ .Values.potProvider.image }}
          args:
          - --port
          - {{ .Values.potProvider.port | toString }}
        {{- end }}
      volumes:
        - name: data
          emptyDir: {}
