---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "huisheng.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "huisheng.labels" . | nindent 4}}
spec:
  selector:
    matchLabels: {{ include "huisheng.selectorLabels" . | nindent 6 }}
  replicas: 1
  strategy: 
    type: Recreate
  template:
    metadata:
      labels: {{ include "huisheng.selectorLabels" . | nindent 8 }}
      annotations:
        credentials/checksum: {{ include (print $.Template.BasePath "/credentials.yaml") . | sha256sum }}
        {{- range $key, $value := range .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      containers:
        - name: huisheng
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          envFrom:
            - secretRef:
                name: {{ .Values.credentials.secretName }}
          env:
            - name: CACHE_DIR
              value: /data
            {{- range $name, $value := .Values.env }}
            - name: {{ $name }}
              value: {{ $value | toString | quote }}
            {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 10000
            runAsGroup: 10000
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ALL]
              add: [SYS_NICE]
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir: {}
