apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: huisheng
  template:
    metadata:
      labels:
        app: huisheng
    spec:
      containers:
        - image: public.ecr.aws/axatol/huisheng:latest
          name: huisheng
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: huisheng-config
            - secretRef:
                name: huisheng-credentials
          securityContext:
            capabilities:
              add:
                - SYS_NICE
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          emptyDir: {}
