apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: huisheng-data-pvc
  namespace: huisheng
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-persistent
  volumeMode: Filesystem
