name: Deploy

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      DISCORD_WEBHOOK_URL:
        required: true

jobs:
  notify:
    runs-on: ${{ github.repository_owner }}-${{ github.event.repository.name }}

    steps:
      - uses: axatol/actions/send-deployment-notification@release
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          status: pending

  deploy:
    needs: notify
    runs-on: self-hosted
    environment: production

    steps:
      - uses: axatol/actions/rollout-kubernetes-deployment@release
        with:
          namespace: huisheng
          deployment-name: huisheng

      - name: Notify deployment complete
        if: success() || failure()
        uses: axatol/actions/send-deployment-notification@release
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          status: ${{ job.status }}
