name: Deploy

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      DISCORD_WEBHOOK_URL:
        required: true
      NEW_RELIC_DEPLOYMENT_ENTITY_GUID:
        required: true
      NEW_RELIC_API_KEY:
        required: true

jobs:
  notify:
    runs-on: self-hosted

    steps:
      - uses: axatol/actions/send-deployment-notification@release
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          status: pending

  deploy:
    needs: notify
    runs-on: self-hosted
    environment: production

    steps:
      - uses: axatol/actions/rollout-kubernetes-deployment@release
        with:
          namespace: huisheng
          deployment-name: huisheng

      - name: Create deployment marker
        if: success()
        uses: axatol/actions/create-newrelic-deployment@release
        with:
          api-key: ${{ secrets.NEW_RELIC_API_KEY }}
          guid: ${{ secrets.NEW_RELIC_DEPLOYMENT_ENTITY_GUID }}
          deployment-type: ROLLING

      - name: Notify deployment complete
        if: success() || failure()
        uses: axatol/actions/send-deployment-notification@release
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          status: ${{ job.status }}
