name: Build

on:
  workflow_dispatch:

  push:
    branches:
      - master

env:
  image: public.ecr.aws/axatol/huisheng

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ECR_IMAGE_PUBLISHER_ROLE_ARN }}
          role-session-name: ${{ github.triggering_actor }}-huisheng-${{ github.job }}-${{ github.run_id }}
          role-skip-session-tagging: true
          role-duration-seconds: 3600

      - uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public

      - uses: axatol/actions/docker-build-push@release
        with:
          image: public.ecr.aws/axatol/huisheng
          build-args: --build-arg GITHUB_SHA=${{ github.sha }}

      - uses: axatol/actions/prune-ecr-repository@release
        with:
          repository-name: axatol/huisheng
