name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: self-hosted

    steps:
      - uses: docker/login-action@v1
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
        env:
          # this seems to be the only endpoint available for ECR?
          AWS_REGION: us-east-1

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: |
          docker pull $IMAGE
          docker build --cache-from $IMAGE --target runtime --build-arg GITHUB_SHA=$GITHUB_SHA -t $IMAGE .
          docker push $IMAGE
        env:
          IMAGE: public.ecr.aws/t4g8t3e5/huisheng:latest
