name: Build

on:
  push:
    branches:
      - master

env:
  image: public.ecr.aws/axatol/huisheng

jobs:
  build:
    name: Build
    runs-on: self-hosted

    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}

      - uses: actions/checkout@v3

      - run: docker tag ${{ env.image }} ${{ env.image }}:previous

      - run: docker push ${{ env.image }}:previous

      - run: |
          docker run --rm \
            -v $(pwd):/workspace \
            -e AWS_ACCESS_KEY \
            -e AWS_SECRET_ACCESS_KEY \
            -e AWS_SDK_LOAD_CONFIG=true \
            gcr.io/kaniko-project/executor:debug \
              --cache \
              --destination=${{ env.image }}:latest \
              --reproducible \
              --target=runtime
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}

      - uses: hans-m-song/actions/prune-ecr-repository@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
          repository-name: huisheng
