name: Build

on:
  push:
    branches:
      - master

env:
  image: public.ecr.aws/axatol/huisheng

jobs:
  build:
    name: Build
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - uses: github/actions-oidc-debugger@main
        with:
          audience: https://sts.amazonaws.com

      - run: |
          arn="${{ secrets.AWS_ECR_IMAGE_PUBLISHER_ROLE_ARN }}"
          echo "length is ${#arn}"

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-southeast-2
          role-to-assume: ${{ secrets.AWS_ECR_IMAGE_PUBLISHER_ROLE_ARN }}
          role-session-name: ${{ github.triggering_actor }}-huisheng-build_image-${{ github.job }}
          role-skip-session-tagging: true
          role-duration-seconds: 3600

      - uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public

      - uses: axatol/actions/docker-build-push@release
        with:
          image: public.ecr.aws/axatol/huisheng
          build-args: --build-arg GITHUB_SHA=${{ github.sha }}
