name: Deploy

on:
  workflow_dispatch:
  workflow_call:

jobs:
  rollout-deployment:
    runs-on: self-hosted
    environment: deep-thought

    steps:
      - run: kubectl rollout restart deployment/huisheng-deployment --namespace huisheng

      - run: kubectl rollout status deployment/huisheng-deployment --namespace huisheng
