name: Deploy

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      DISCORD_GITHUB_ACTIONS_WEBHOOK_URL:
        required: true
      NEW_RELIC_API_KEY:
        required: true
      NEW_RELIC_DEPLOYMENT_ENTITY_GUID:
        required: true

env:
  STATUS_COLOR: 255

jobs:
  notify:
    runs-on: self-hosted

    steps:
      - uses: axatol/actions/send-discord-deployment-notification@release
        with:
          webhook-url: ${{ secrets.DISCORD_GITHUB_ACTIONS_WEBHOOK_URL }}
          status: pending

  deploy:
    needs: notify
    runs-on: self-hosted
    environment: wheatley

    steps:
      - name: Rollout deployment
        uses: axatol/actions/rollout-kubernetes-deployment@release
        id: deploy
        with:
          deployment-name: huisheng
          namespace: huisheng
          wait: true

      - name: Create deployment marker
        if: success()
        uses: axatol/actions/create-new-relic-deployment@release
        with:
          name: huisheng
          api-key: ${{ secrets.NEW_RELIC_API_KEY }}
          deployment-type: ROLLING

      - name: Notify deployment complete
        if: success() || failure()
        uses: axatol/actions/send-discord-deployment-notification@release
        with:
          webhook-url: ${{ secrets.DISCORD_GITHUB_ACTIONS_WEBHOOK_URL }}
          status: ${{ steps.deploy.outcome }}
