name: Deploy

on:
  workflow_dispatch:
  workflow_call:

jobs:
  rollout-deployment:
    runs-on: self-hosted
    environment: deep-thought

    steps:
      - id: old
        run: |
          old=$( kubectl -n huisheng get pods -o=jsonpath='{.items[].metadata.name}' )
          echo "old=$old" >> $GITHUB_OUTPUT

      - run: kubectl rollout restart deployment/huisheng-deployment --namespace huisheng

      - run: kubectl rollout status deployment/huisheng-deployment --namespace huisheng

      - env:
          old: ${{ steps.old.outputs.old }}
        run: kubectl wait --for=delete --namespace huisheng pods/$old
