name: Deploy

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      DISCORD_GITHUB_ACTIONS_WEBHOOK_URL:
        required: true
      NEW_RELIC_API_KEY:
        required: true
      NEW_RELIC_DEPLOYMENT_ENTITY_GUID:
        required: true

env:
  STATUS_COLOR: 255

jobs:
  deploy:
    runs-on: self-hosted
    environment: deep-thought

    steps:
      - name: Notify deployment begins
        shell: python
        run: |
          import requests

          requests.post("${{ secrets.DISCORD_GITHUB_ACTIONS_WEBHOOK_URL }}", json={
            "embeds": [{
              "title": "Deployment pending review",
              "type": "rich",
              "color": 16170496,
              "description": "\n".join([
                "Run conclusion: ${{ job.status }}
                "- [Workflow run](${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }})",
                "- [Repository](${{ github.event.repository.html_url }})",
                "- [Deployment history](${{ github.event.repository.html_url }}/deployments/activity_log)",
              ]),
            }]
          })

      - name: Rollout deployment
        uses: axatol/actions/rollout-kubernetes-deployment@release
        id: deploy
        with:
          deployment-name: huisheng
          namespace: huisheng
          wait: true

      - name: Create deployment marker
        if: success()
        uses: axatol/actions/create-new-relic-deployment@release
        with:
          name: huisheng
          api-key: ${{ secrets.NEW_RELIC_API_KEY }}
          deployment-type: ROLLING

      - if: success()
        run: echo "STATUS_COLOR=65280" >> $GITHUB_ENV || true

      - if: failure()
        run: echo "STATUS_COLOR=16711680" >> $GITHUB_ENV || true

      - name: Notify deployment complete
        if: success() || failure()
        shell: python
        run: |
          import requests

          requests.post("${{ secrets.DISCORD_GITHUB_ACTIONS_WEBHOOK_URL }}", json={
            "embeds": [{
              "title": "Deployment complete",
              "type": "rich",
              "color": ${{ env.STATUS_COLOR }},
              "description": "\n".join([
                "Run conclusion: ${{ job.status }}
                "- [Workflow run](${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }})",
                "- [Repository](${{ github.event.repository.html_url }})",
                "- [Deployment history](${{ github.event.repository.html_url }}/deployments/activity_log)",
              ]),
            }]
          })
