name: Deploy

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      DISCORD_GITHUB_ACTIONS_WEBHOOK_URL:
        required: true
      NEW_RELIC_API_KEY:
        required: true
      NEW_RELIC_DEPLOYMENT_ENTITY_GUID:
        required: true

env:
  NAMESPACE: --namespace huisheng
  DEPLOYMENT: deployment/huisheng-deployment
  STATUS_COLOR: 255

jobs:
  notify-deployment:
    runs-on: self-hosted

    steps:
      - run: |
          curl ${{ secrets.DISCORD_GITHUB_ACTIONS_WEBHOOK_URL }} \
            --request POST \
            --header 'Content-Type: application/json' \
            --data '{
              "embeds": [
                {
                  "title": "Deployment pending review",
                  "type": "rich",
                  "description": "- [Workflow run](${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }})\n- [Repository](${{ github.event.repository.html_url }})\n- [Deployment history](${{ github.event.repository.html_url }}/deployments/activity_log)",
                  "color": 16170496
                }
              ]
            }'

  rollout-deployment:
    needs: notify-deployment
    runs-on: self-hosted
    environment: deep-thought

    steps:
      - run: echo "OLD_NAME=$( kubectl $NAMESPACE get pods -o=jsonpath='{.items[].metadata.name}' )" >> $GITHUB_ENV

      - run: kubectl rollout restart $NAMESPACE $DEPLOYMENT

      - run: kubectl rollout status $NAMESPACE $DEPLOYMENT

      - run: kubectl wait $NAMESPACE --for=delete --timeout 5m pods/$OLD_NAME

      - id: date
        run: echo "date=$(date +"%Y-%m-%d-%H-%M-%S")" >> $GITHUB_OUTPUT

      - if: success()
        uses: newrelic/deployment-marker-action@v2.4.0
        with:
          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
          guid: ${{ secrets.NEW_RELIC_DEPLOYMENT_ENTITY_GUID }}
          version: ${{ steps.date.outputs.date }}
          user: ${{ github.actor }}
          commit: ${{ github.sha }}
          deeplink: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - if: success()
        run: echo "STATUS_COLOR=65280" >> $GITHUB_ENV || true

      - if: failure()
        run: echo "STATUS_COLOR=16711680" >> $GITHUB_ENV || true

      - if: success() || failure()
        run: |
          curl ${{ secrets.DISCORD_GITHUB_ACTIONS_WEBHOOK_URL }} \
            --request POST \
            --header 'Content-Type: application/json' \
            --data '{
              "embeds": [
                {
                  "title": "Deployment complete",
                  "type": "rich",
                  "description": "Run conclusion: ${{ job.status }}\n- [Workflow run](${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }})\n- [Repository](${{ github.event.repository.html_url }})\n- [Deployment history](${{ github.event.repository.html_url }}/deployments/activity_log)",
                  "color": "${{ env.STATUS_COLOR }}"
                }
              ]
            }'
