name: Manage Deployment

on:
  workflow_dispatch:
    inputs:
      action:
        description: Action to execute
        type: choice
        required: true
        options:
          - restart
          - deploy

jobs:
  restart:
    runs-on: self-hosted
    environment: deep-thought
    if: inputs.action == 'restart'
    steps:
      - run: kubectl rollout restart deployment/huisheng-deployment --namespace huisheng

  deploy:
    runs-on: self-hosted
    environment: deep-thought
    if: inputs.action == 'deploy'
    steps:
      - uses: actions/checkout@v3
      - run: kubectl deploy -k manifests
