name: Merge to master

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build-image.yml

  deploy:
    needs: build
    uses: ./.github/workflows/manage-deployment.yml
    with:
      action: restart
