name: Merge to master

on:
  push:
    branches:
      - master

  workflow_dispatch:
    inputs:
      disable-cache:
        description: Disable cache
        required: false
        default: false
        type: boolean

permissions:
  id-token: write
  contents: read

jobs:
  build-image:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ECR_IMAGE_PUBLISHER_ROLE_ARN }}
          role-session-name: ${{ github.triggering_actor }}-huisheng-${{ github.job }}-${{ github.run_id }}
          role-skip-session-tagging: true
          role-duration-seconds: 3600

      - uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public

      - uses: axatol/actions/docker-build-push@release
        with:
          image: public.ecr.aws/axatol/huisheng
          build-args: --build-arg GITHUB_SHA=${{ github.sha }}
          use-cache: ${{ inputs.disable-cache != 'true' }}

      - uses: axatol/actions/prune-ecr-repository@release
        with:
          repository-name: ${{ env.image }}

  restart-deployment:
    needs: build-image
    if: inputs.action == 'restart'
    runs-on: self-hosted
    environment: deep-thought
    steps:
      - run: kubectl rollout restart deployment/huisheng-deployment --namespace huisheng
