name: Push to charts

on:
  push:
    branches:
      - master
    paths:
      - './charts/**'
      - ./.github/workflows/push-to-charts.yml

jobs:
  release:
    runs-on:
      - self-hosted

    steps:
      - uses: actions/checkout@v3

      - run: git config user.name "$GITHUB_ACTOR"

      - run: git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - uses: helm/chart-releaser-action@v1
