name: Push to master

on:
  push:
    branches:
      - master

  workflow_dispatch:

env:
  image: public.ecr.aws/axatol/huisheng

jobs:
  check-code:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - run: npm install

      - run: npm run lint

      - run: npm run compile

  build-image:
    needs: check-code
    runs-on: self-hosted

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - uses: github/actions-oidc-debugger@main
        with:
          audience: sts.amazonaws.com

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ECR_IMAGE_PUBLISHER_ROLE_ARN }}
          role-session-name: ${{ github.triggering_actor }}-${{ github.event.repository.name }}-${{ github.job }}-${{ github.run_id }}
          role-skip-session-tagging: true
          role-duration-seconds: 3600

      - uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public

      - uses: axatol/actions/docker-build-push@release
        with:
          image: ${{ env.image }}
          build-args: --build-arg GITHUB_SHA=${{ github.sha }}

      - uses: axatol/actions/prune-ecr-repository@release
        with:
          repository-name: ${{ env.image }}

  restart-deployment:
    needs: build-image
    runs-on: self-hosted
    environment: deep-thought
    steps:
      - run: kubectl rollout restart deployment/huisheng-deployment --namespace huisheng
