name: Push to master

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'charts/**'
      - '.github/workflows/push-to-charts.yml'

  workflow_dispatch:

jobs:
  build-image:
    uses: ./.github/workflows/_build.yml

  restart-deployment:
    needs: build-image
    uses: ./.github/workflows/_deploy.yml
    secrets:
      DISCORD_GITHUB_ACTIONS_WEBHOOK_URL: ${{ secrets.DISCORD_GITHUB_ACTIONS_WEBHOOK_URL }}
      NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
      NEW_RELIC_DEPLOYMENT_ENTITY_GUID: ${{ secrets.NEW_RELIC_DEPLOYMENT_ENTITY_GUID }}
