name: Push to master

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'charts/**'
      - '.github/workflows/push-to-charts.yml'

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      publish: true
    secrets:
      AWS_ECR_IMAGE_PUBLISHER_ROLE_ARN: ${{ secrets.AWS_ECR_IMAGE_PUBLISHER_ROLE_ARN }}

  deploy:
    needs: build
    uses: ./.github/workflows/_deploy.yml
    secrets:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      NEW_RELIC_DEPLOYMENT_ENTITY_GUID: ${{ secrets.NEW_RELIC_DEPLOYMENT_ENTITY_GUID }}
