name: Push to charts

on:
  workflow_dispatch:

  push:
    branches:
      - master
    paths:
      - 'charts/**'
      - '.github/workflows/push-to-charts.yml'

jobs:
  release:
    runs-on:
      - self-hosted

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - id: release
        uses: helm/chart-releaser-action@v1
        env:
          CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - run: |
          echo "chart version: ${{ steps.release.outputs.chart_version }}"
